export BWRAP_STAGE1_VERSION="0.6.2"
export BWRAP_STAGE1_ARCHIVE="bubblewrap-${BWRAP_STAGE1_VERSION}.tar.gz"
export BWRAP_STAGE1_DOWNLOAD_URL="https://github.com/containers/bubblewrap/archive/refs/tags/v${BWRAP_STAGE1_VERSION}.tar.gz"
export BWRAP_STAGE1_SOURCE_DIR="${SOURCE_DIR}/cache/bubblewrap-${BWRAP_STAGE1_VERSION}"
export BWRAP_STAGE1_INSTALL_DIR="${CACHE_INSTALL_DIR}/bwrap/stage1"
export BWRAP_STAGE1_BIN_DIR="${BWRAP_STAGE1_INSTALL_DIR}/bin"
